version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/bread_shop_v2
    docker:
      - image: circleci/ruby:3.0.0-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: bread_shop_v2
          RAILS_ENV: test
      - image: postgres:12
        environment:
          POSTGRES_USER: bread_shop_v2
          POSTGRES_DB: bread_shop_v2_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: bread_shop_v2-{{ checksum "Gemfile.lock" }}
      - run:
          name: Configure Bundler
          command:
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      # Bundle Install Dependencies
      - run: bundle install --path vendor/bundle
      # Cache dependencies
      - type: cache-save
        name: Store bundle cache
        key: bread_shop_v2-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Setup database
      - run: bundle exec rake db:{drop,create,migrate,seed}
      - run: yarn install
      - run: bin/rails webpacker:compile
      # Run tests
      - run: bundle exec rspec
